---
- name: Web Page Deployment
  hosts: localhost
  become: yes  # Enables sudo for tasks without prompting for a password

  tasks:
    - name: Apache HTTP Server installing
      yum:
        name: httpd
        state: present

    - name: Start and Enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy Web Files
      copy:
        src: "{{ playbook_dir }}/"
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
